name: Latest activity

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  get-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: Readme-Workflows/recent-activity@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_ITEMS: 10