name: Update Profile with Gemini Quote

on:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 2:00 AM UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install google-generativeai

      - name: Generate and Update README
        run: python .github/scripts/generate_text.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat: Update Gemini quote"
          file_pattern: 'README.md'

      - name: Generate tech fact with Gemini
        id: gemini-fact
        uses: google-github-actions/run-gemini-cli@main
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: 'Generate a short, fascinating fact about computer science, software, or technology history.'

      - name: Update README.md
        run: |
          echo "### 💡 Daily Tech Fact" > FACT.md
          echo "" >> FACT.md
          echo "${{ steps.gemini-fact.outputs.output }}" >> FACT.md
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add FACT.md
          git commit -m "🤖 Update daily tech fact" || exit 0
          git push